{{- $fullName := include "iot-ingress.fullname" . -}}
{{- $ingressClass := .Values.ingress.controller.ingressClass -}}
apiVersion:  networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: {{ $ingressClass }}
    cert-manager.io/issuer: ingress-iot-ingress
    nginx.ingress.kubernetes.io/enable-rewrite-log: "{{ .Values.config.rewriteLog }}"


  labels:
    app.kubernetes.io/name: {{ include "iot-ingress.name" . }}
    helm.sh/chart: {{ include "iot-ingress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
{{ toYaml .Values.ingressSpec | indent 2 }}
